import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';
import { RepomixEngine } from './repomixEngine';
import { EngineResult, GenerateResult, FileNode } from '../types';

export class ContextEngine {
    private repomix: RepomixEngine;
    private _lastResult: GenerateResult | null = null;
    private _onDidUpdate = new vscode.EventEmitter<GenerateResult>();
    readonly onDidUpdate = this._onDidUpdate.event;

    constructor(private workspaceRoot: string) {
        this.repomix = new RepomixEngine(workspaceRoot);
    }

    get lastResult(): GenerateResult | null {
        return this._lastResult;
    }

    get lastTree(): FileNode | null {
        return this._lastResult?.result?.tree ?? null;
    }

    async generate(): Promise<GenerateResult> {
        const config = vscode.workspace.getConfiguration('crawlerSage');
        const style = config.get<string>('outputStyle', 'xml');
        const compress = config.get<boolean>('compress', true);

        const result = await this.repomix.run(style, compress);

        const outputFile = config.get<string>('outputFile', '.context.md');
        const outputPath = path.join(this.workspaceRoot, outputFile);

        // Write a lean summary file
        const summary = this.buildSummary(result, style);
        fs.writeFileSync(outputPath, summary, 'utf-8');

        const generateResult: GenerateResult = {
            totalFiles: result.fileCount,
            totalTokens: result.tokenCount,
            totalChars: result.charCount,
            timestamp: new Date(),
            result,
            outputPath
        };

        this._lastResult = generateResult;
        this._onDidUpdate.fire(generateResult);

        return generateResult;
    }

    private buildSummary(result: EngineResult, style: string): string {
        const timestamp = new Date().toISOString();
        const ext = style === 'xml' ? 'xml' : 'md';

        let s = `# Codebase Context\n\n`;
        s += `> Generated by [Crawler Sage](https://github.com/pudiish/crawler-sage) at ${timestamp}\n\n`;
        s += `| Metric | Value |\n|--------|-------|\n`;
        s += `| Files | ${result.fileCount} |\n`;
        s += `| Tokens | ~${result.tokenCount.toLocaleString()} |\n`;
        s += `| Characters | ${result.charCount.toLocaleString()} |\n`;
        s += `| Style | ${style} (tree-sitter compressed) |\n`;
        s += `| Duration | ${result.duration}ms |\n\n`;
        s += `## Full Output\n\n`;
        s += `\`.crawler-sage/repomix-output.${ext}\`\n\n`;
        s += `## Directory Structure\n\n`;
        s += `\`\`\`\n`;
        s += this.renderTree(result.tree, '');
        s += `\`\`\`\n`;

        return s;
    }

    private renderTree(node: FileNode, indent: string): string {
        let out = '';
        if (node.children) {
            for (let i = 0; i < node.children.length; i++) {
                const child = node.children[i];
                const isLast = i === node.children.length - 1;
                const prefix = isLast ? '└── ' : '├── ';
                const nextIndent = indent + (isLast ? '    ' : '│   ');
                out += `${indent}${prefix}${child.name}${child.type === 'directory' ? '/' : ''}\n`;
                if (child.children) {
                    out += this.renderTree(child, nextIndent);
                }
            }
        }
        return out;
    }
}
